### ISSUE TITLE
Move to ckan organization on GitHub

### ISSUE THREAD

**Issue by amercader** [datopian/pytest-ckan#3]
pytest-ckan has proven invaluable for extensions with cross-CKAN version support, and is included as dev requirement in the [default extension template](https://github.com/ckan/ckan/blob/70db2188bc9f9c45e7885a8c7d402c0755544a46/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/dev-requirements.txt). To help with maintenance going forward what do you think about moving this to the ckan organization and give access to tech team members representatives to PyPI?

**Comment by amercader** [comment]
@shevron wdyt?

**Comment by shevron** [comment]
@amercader I'm all for it, I see more value in maintaining this under the `ckan` organization than keeping it here.

**Comment by shevron** [comment]
We can either just transfer this repo to the `ckan` org (/cc @rufuspollock if you're OK with this), or you can fork it, and I'll archive this one.

**Comment by amercader** [comment]
@shevron I forked the repo on the ckan org. Can you give me access to Pypi?

**Comment by shevron** [comment]
@amercader email / DM me your pypi user name (or put here if you don't mind)

**Comment by shevron** [comment]
hmm... nvm found it

**Comment by shevron** [comment]
done
